/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenGardenRouteImport } from './routes/zen-garden'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PixelDojoRouteImport } from './routes/pixel-dojo'
import { Route as ParchmentRouteImport } from './routes/parchment'
import { Route as ObsidianRouteImport } from './routes/obsidian'
import { Route as NeonArenaRouteImport } from './routes/neon-arena'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameRoomIdRouteImport } from './routes/game.$roomId'

const ZenGardenRoute = ZenGardenRouteImport.update({
  id: '/zen-garden',
  path: '/zen-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelDojoRoute = PixelDojoRouteImport.update({
  id: '/pixel-dojo',
  path: '/pixel-dojo',
  getParentRoute: () => rootRouteImport,
} as any)
const ParchmentRoute = ParchmentRouteImport.update({
  id: '/parchment',
  path: '/parchment',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsidianRoute = ObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => rootRouteImport,
} as any)
const NeonArenaRoute = NeonArenaRouteImport.update({
  id: '/neon-arena',
  path: '/neon-arena',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/zen-garden': typeof ZenGardenRoute
  '/game/$roomId': typeof GameRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/zen-garden': typeof ZenGardenRoute
  '/game/$roomId': typeof GameRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/zen-garden': typeof ZenGardenRoute
  '/game/$roomId': typeof GameRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/signin'
    | '/signup'
    | '/zen-garden'
    | '/game/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/signin'
    | '/signup'
    | '/zen-garden'
    | '/game/$roomId'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/signin'
    | '/signup'
    | '/zen-garden'
    | '/game/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
  NeonArenaRoute: typeof NeonArenaRoute
  ObsidianRoute: typeof ObsidianRoute
  ParchmentRoute: typeof ParchmentRoute
  PixelDojoRoute: typeof PixelDojoRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ZenGardenRoute: typeof ZenGardenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zen-garden': {
      id: '/zen-garden'
      path: '/zen-garden'
      fullPath: '/zen-garden'
      preLoaderRoute: typeof ZenGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-dojo': {
      id: '/pixel-dojo'
      path: '/pixel-dojo'
      fullPath: '/pixel-dojo'
      preLoaderRoute: typeof PixelDojoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parchment': {
      id: '/parchment'
      path: '/parchment'
      fullPath: '/parchment'
      preLoaderRoute: typeof ParchmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obsidian': {
      id: '/obsidian'
      path: '/obsidian'
      fullPath: '/obsidian'
      preLoaderRoute: typeof ObsidianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neon-arena': {
      id: '/neon-arena'
      path: '/neon-arena'
      fullPath: '/neon-arena'
      preLoaderRoute: typeof NeonArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameRoomIdRoute: typeof GameRoomIdRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameRoomIdRoute: GameRoomIdRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
  NeonArenaRoute: NeonArenaRoute,
  ObsidianRoute: ObsidianRoute,
  ParchmentRoute: ParchmentRoute,
  PixelDojoRoute: PixelDojoRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ZenGardenRoute: ZenGardenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
