/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerUsernameRouteImport } from './routes/player.$username'
import { Route as GameRoomIdRouteImport } from './routes/game.$roomId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AnalyseRoomIdRouteImport } from './routes/analyse.$roomId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUsernameRoute = PlayerUsernameRouteImport.update({
  id: '/player/$username',
  path: '/player/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomIdRoute = GameRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => GameRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoomIdRoute = AnalyseRoomIdRouteImport.update({
  id: '/analyse/$roomId',
  path: '/analyse/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/history': typeof HistoryRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analyse/$roomId': typeof AnalyseRoomIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/history': typeof HistoryRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analyse/$roomId': typeof AnalyseRoomIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/history': typeof HistoryRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/analyse/$roomId': typeof AnalyseRoomIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/game/$roomId': typeof GameRoomIdRoute
  '/player/$username': typeof PlayerUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/history'
    | '/signin'
    | '/signup'
    | '/analyse/$roomId'
    | '/auth/callback'
    | '/game/$roomId'
    | '/player/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/history'
    | '/signin'
    | '/signup'
    | '/analyse/$roomId'
    | '/auth/callback'
    | '/game/$roomId'
    | '/player/$username'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/history'
    | '/signin'
    | '/signup'
    | '/analyse/$roomId'
    | '/auth/callback'
    | '/game/$roomId'
    | '/player/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AnalyseRoomIdRoute: typeof AnalyseRoomIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlayerUsernameRoute: typeof PlayerUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$username': {
      id: '/player/$username'
      path: '/player/$username'
      fullPath: '/player/$username'
      preLoaderRoute: typeof PlayerUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomId': {
      id: '/game/$roomId'
      path: '/$roomId'
      fullPath: '/game/$roomId'
      preLoaderRoute: typeof GameRoomIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/$roomId': {
      id: '/analyse/$roomId'
      path: '/analyse/$roomId'
      fullPath: '/analyse/$roomId'
      preLoaderRoute: typeof AnalyseRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GameRouteChildren {
  GameRoomIdRoute: typeof GameRoomIdRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameRoomIdRoute: GameRoomIdRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
  HistoryRoute: HistoryRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AnalyseRoomIdRoute: AnalyseRoomIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PlayerUsernameRoute: PlayerUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
