/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenGardenRouteImport } from './routes/zen-garden'
import { Route as PixelDojoRouteImport } from './routes/pixel-dojo'
import { Route as ParchmentRouteImport } from './routes/parchment'
import { Route as ObsidianRouteImport } from './routes/obsidian'
import { Route as NeonArenaRouteImport } from './routes/neon-arena'
import { Route as IndexRouteImport } from './routes/index'

const ZenGardenRoute = ZenGardenRouteImport.update({
  id: '/zen-garden',
  path: '/zen-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const PixelDojoRoute = PixelDojoRouteImport.update({
  id: '/pixel-dojo',
  path: '/pixel-dojo',
  getParentRoute: () => rootRouteImport,
} as any)
const ParchmentRoute = ParchmentRouteImport.update({
  id: '/parchment',
  path: '/parchment',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsidianRoute = ObsidianRouteImport.update({
  id: '/obsidian',
  path: '/obsidian',
  getParentRoute: () => rootRouteImport,
} as any)
const NeonArenaRoute = NeonArenaRouteImport.update({
  id: '/neon-arena',
  path: '/neon-arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/zen-garden': typeof ZenGardenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/zen-garden': typeof ZenGardenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/neon-arena': typeof NeonArenaRoute
  '/obsidian': typeof ObsidianRoute
  '/parchment': typeof ParchmentRoute
  '/pixel-dojo': typeof PixelDojoRoute
  '/zen-garden': typeof ZenGardenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/zen-garden'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/zen-garden'
  id:
    | '__root__'
    | '/'
    | '/neon-arena'
    | '/obsidian'
    | '/parchment'
    | '/pixel-dojo'
    | '/zen-garden'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NeonArenaRoute: typeof NeonArenaRoute
  ObsidianRoute: typeof ObsidianRoute
  ParchmentRoute: typeof ParchmentRoute
  PixelDojoRoute: typeof PixelDojoRoute
  ZenGardenRoute: typeof ZenGardenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zen-garden': {
      id: '/zen-garden'
      path: '/zen-garden'
      fullPath: '/zen-garden'
      preLoaderRoute: typeof ZenGardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixel-dojo': {
      id: '/pixel-dojo'
      path: '/pixel-dojo'
      fullPath: '/pixel-dojo'
      preLoaderRoute: typeof PixelDojoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parchment': {
      id: '/parchment'
      path: '/parchment'
      fullPath: '/parchment'
      preLoaderRoute: typeof ParchmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obsidian': {
      id: '/obsidian'
      path: '/obsidian'
      fullPath: '/obsidian'
      preLoaderRoute: typeof ObsidianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neon-arena': {
      id: '/neon-arena'
      path: '/neon-arena'
      fullPath: '/neon-arena'
      preLoaderRoute: typeof NeonArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NeonArenaRoute: NeonArenaRoute,
  ObsidianRoute: ObsidianRoute,
  ParchmentRoute: ParchmentRoute,
  PixelDojoRoute: PixelDojoRoute,
  ZenGardenRoute: ZenGardenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
